// <auto-generated />
using System;
using BD.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BD.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20201025022304_AddTrackableToRole")]
    partial class AddTrackableToRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BD.Business.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "bd14b71d-2360-4eb8-9253-f365f5da30a6",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("BD.Business.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f00206a7-f2b2-4b6f-a97b-49c7574fee8f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFf7TCrCxcMIRZdq58bsTeMYSCMNZEZESs5xHRueC0egDIoYPtVdIC05HYZ0gu1UcA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2234d5dc-2565-4a77-9f2a-76e48fc44788",
                            TwoFactorEnabled = false,
                            UpdatedBy = 0,
                            UserName = "admin@admin.com"
                        });
                });

            modelBuilder.Entity("BD.Business.Models.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<int?>("ReserveId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReserveId");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("BD.Business.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(180)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BD.Business.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(5542),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(5554),
                            Name = "Listar Usuários",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6406),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6413),
                            Name = "Visualizar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6431),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6433),
                            Name = "Adicionar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6435),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6437),
                            Name = "Alterar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6440),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6441),
                            Name = "Desativar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6450),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6451),
                            Name = "Reativar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6455),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6456),
                            Name = "Trocar Senha",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "ChangePassword"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6459),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6460),
                            Name = "Trocar Senha de outro Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "ChangeUserPassword"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6463),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6465),
                            Name = "Listar Funções",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6469),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6471),
                            Name = "Visualizar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6474),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6475),
                            Name = "Adicionar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6478),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6480),
                            Name = "Alterar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6482),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6484),
                            Name = "Apagar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6489),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6490),
                            Name = "Adicionar Permissão a Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "AddClaim"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6493),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6495),
                            Name = "Remover Permissão da Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "DeleteClaim"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6497),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6499),
                            Name = "Listar Reservas",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6501),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6503),
                            Name = "Visualizar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6507),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6509),
                            Name = "Adicionar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6512),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6513),
                            Name = "Alterar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6516),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6518),
                            Name = "Desativar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6520),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6522),
                            Name = "Reativar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6524),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6526),
                            Name = "Listar Itens",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6529),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6530),
                            Name = "Visualizar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6533),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6535),
                            Name = "Adicionar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6537),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6539),
                            Name = "Alterar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6541),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6543),
                            Name = "Desativar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6546),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6547),
                            Name = "Reativar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6550),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6551),
                            Name = "Listar Permissões",
                            Type = "Permission",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6554),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6556),
                            Name = "Listar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6558),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6560),
                            Name = "Visualizar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6562),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6564),
                            Name = "Adicionar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6567),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6568),
                            Name = "Alterar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6571),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6573),
                            Name = "Desativar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6577),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 24, 23, 23, 3, 74, DateTimeKind.Local).AddTicks(6579),
                            Name = "Reativar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        });
                });

            modelBuilder.Entity("BD.Business.Models.Reserve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Entry")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("BD.Business.Models.ReserveItem", b =>
                {
                    b.Property<int>("IdReserveItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReserveId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdReserveItem");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReserveId");

                    b.ToTable("ReserveItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("BD.Business.Models.CashFlow", b =>
                {
                    b.HasOne("BD.Business.Models.Reserve", "Reserve")
                        .WithMany("CashFlows")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BD.Business.Models.ReserveItem", b =>
                {
                    b.HasOne("BD.Business.Models.Item", "Item")
                        .WithMany("ReserveItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BD.Business.Models.Reserve", "Reserve")
                        .WithMany("ReserveItem")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
