// <auto-generated />
using System;
using BD.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BD.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BD.Business.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "b9b68ab1-12ca-41e3-ae75-8d81215b4959",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("BD.Business.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00e5f176-01d4-4357-bb3f-ea7efb0dc4d1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKBoCnntZGprfHcBjuZ9bqBK9vn9amUDhMIchTIhHE1OnGlCKlK/v5QXq7O+6V0KLg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9b847b25-2e78-432f-8831-82625b38abbe",
                            TwoFactorEnabled = false,
                            UpdatedBy = 0,
                            UserName = "admin@admin.com"
                        });
                });

            modelBuilder.Entity("BD.Business.Models.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<int?>("ReserveId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReserveId");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("BD.Business.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(180)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BD.Business.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(1700),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(1730),
                            Name = "Listar Usuários",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2325),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2330),
                            Name = "Visualizar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2343),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2344),
                            Name = "Adicionar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2348),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2349),
                            Name = "Alterar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2352),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2353),
                            Name = "Desativar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2359),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2360),
                            Name = "Reativar Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2362),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2363),
                            Name = "Trocar Senha",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "ChangePassword"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2365),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2366),
                            Name = "Trocar Senha de outro Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "ChangeUserPassword"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2368),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2369),
                            Name = "Atualizar Grupos de um Usuário",
                            Type = "User",
                            UpdatedBy = 0,
                            Value = "UpdateRoles"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2372),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2373),
                            Name = "Listar Funções",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2375),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2376),
                            Name = "Visualizar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2378),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2379),
                            Name = "Adicionar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2381),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2382),
                            Name = "Alterar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2384),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2385),
                            Name = "Apagar Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2387),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2388),
                            Name = "Adicionar Permissão a Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "AddClaim"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2390),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2391),
                            Name = "Remover Permissão da Função",
                            Type = "Role",
                            UpdatedBy = 0,
                            Value = "DeleteClaim"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2393),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2394),
                            Name = "Listar Reservas",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2398),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2399),
                            Name = "Visualizar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2401),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2402),
                            Name = "Adicionar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2404),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2405),
                            Name = "Alterar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2407),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2408),
                            Name = "Desativar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2410),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2411),
                            Name = "Reativar Reserva",
                            Type = "Reserve",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2413),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2414),
                            Name = "Listar Itens",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2416),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2417),
                            Name = "Visualizar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2419),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2420),
                            Name = "Adicionar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2423),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2424),
                            Name = "Alterar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2426),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2427),
                            Name = "Desativar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2429),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2430),
                            Name = "Reativar Item",
                            Type = "Item",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2432),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2433),
                            Name = "Listar Permissões",
                            Type = "Permission",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2435),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2436),
                            Name = "Listar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "All"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2438),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2439),
                            Name = "Visualizar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Get"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2441),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2442),
                            Name = "Adicionar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2444),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2445),
                            Name = "Alterar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2449),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2450),
                            Name = "Desativar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Disable"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2545),
                            CreatedBy = 0,
                            DisabledBy = 0,
                            LastUpdatedAt = new DateTime(2020, 10, 25, 16, 24, 31, 227, DateTimeKind.Local).AddTicks(2547),
                            Name = "Reativar Fluxo de Caixa",
                            Type = "CashFlow",
                            UpdatedBy = 0,
                            Value = "Reactive"
                        });
                });

            modelBuilder.Entity("BD.Business.Models.Reserve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Entry")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("BD.Business.Models.ReserveItem", b =>
                {
                    b.Property<int>("IdReserveItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisabledBy")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReserveId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdReserveItem");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReserveId");

                    b.ToTable("ReserveItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("BD.Business.Models.CashFlow", b =>
                {
                    b.HasOne("BD.Business.Models.Reserve", "Reserve")
                        .WithMany("CashFlows")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BD.Business.Models.ReserveItem", b =>
                {
                    b.HasOne("BD.Business.Models.Item", "Item")
                        .WithMany("ReserveItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BD.Business.Models.Reserve", "Reserve")
                        .WithMany("ReserveItem")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BD.Business.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
